from __future__ import annotations

from ..quality.awap.contracts import (
    GoldDatasetContract,
    GoldLoadStrategy,
    ReconciliationRule,
    RefreshCadence,
)
from ..schemas.gold_schema import (
    AccountDimensionSchema,
    AccountMonthlySnapshotFactSchema,
    AccountOwnerFactlessSchema,
    AccountTransactionFactSchema,
    CurrencyDimensionSchema,
    CustomerDimensionSchema,
    DateDimensionSchema,
    LocationDimensionSchema,
    MerchantDimensionSchema,
    TemporalTrendFactSchema,
    TimeDimensionSchema,
    TransactionTypeDimensionSchema,
    TransErrorTypeDimensionSchema,
)


GOLD_CONTRACTS: dict[str, GoldDatasetContract] = {
    "date_dimension": GoldDatasetContract(
        name="date_dimension",
        schema=DateDimensionSchema,
        staging_path="gold/_staging/date_dimension",
        publish_path="gold/date_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.ONE_TIME,
        description="Static calendar snapshot used as a reference dimension.",
        source_names=("transactions",),
        required_columns=("date_key", "full_date"),
        unique_key=("date_key",),
    ),
    "time_dimension": GoldDatasetContract(
        name="time_dimension",
        schema=TimeDimensionSchema,
        staging_path="gold/_staging/time_dimension",
        publish_path="gold/time_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.ONE_TIME,
        description="Static 24-hour time snapshot used as a reference dimension.",
        required_columns=("time_key",),
        unique_key=("time_key",),
    ),
    "customer_dimension": GoldDatasetContract(
        name="customer_dimension",
        schema=CustomerDimensionSchema,
        staging_path="gold/_staging/customer_dimension",
        publish_path="gold/customer_dimension",
        load_strategy=GoldLoadStrategy.CDC_UPSERT,
        refresh_cadence=RefreshCadence.CDC,
        description="Mutable customer dimension with SCD-style version fields.",
        source_names=("users",),
        required_columns=(
            "customer_key",
            "customer_id",
            "effective_from_date",
            "effective_to_date",
            "is_current",
            "version_number",
        ),
        unique_key=("customer_key",),
        cdc_key=("customer_key",),
    ),
    "account_dimension": GoldDatasetContract(
        name="account_dimension",
        schema=AccountDimensionSchema,
        staging_path="gold/_staging/account_dimension",
        publish_path="gold/account_dimension",
        load_strategy=GoldLoadStrategy.CDC_UPSERT,
        refresh_cadence=RefreshCadence.CDC,
        description="Mutable account/card dimension with SCD-style version fields.",
        source_names=("cards",),
        required_columns=(
            "account_key",
            "account_id",
            "effective_from_date",
            "effective_to_date",
            "is_current",
            "version_number",
        ),
        unique_key=("account_key",),
        cdc_key=("account_key",),
    ),
    "merchant_dimension": GoldDatasetContract(
        name="merchant_dimension",
        schema=MerchantDimensionSchema,
        staging_path="gold/_staging/merchant_dimension",
        publish_path="gold/merchant_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.FULL_REFRESH,
        description="MCC reference snapshot, replaced in full when source changes.",
        source_names=("mcc",),
        required_columns=("merchant_key",),
        unique_key=("merchant_key",),
    ),
    "location_dimension": GoldDatasetContract(
        name="location_dimension",
        schema=LocationDimensionSchema,
        staging_path="gold/_staging/location_dimension",
        publish_path="gold/location_dimension",
        load_strategy=GoldLoadStrategy.CDC_UPSERT,
        refresh_cadence=RefreshCadence.CDC,
        description="Location dimension derived from mutable users and transactions.",
        source_names=("users", "transactions"),
        required_columns=("location_key",),
        unique_key=("location_key",),
        cdc_key=("location_key",),
    ),
    "transaction_type_dimension": GoldDatasetContract(
        name="transaction_type_dimension",
        schema=TransactionTypeDimensionSchema,
        staging_path="gold/_staging/transaction_type_dimension",
        publish_path="gold/transaction_type_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.FULL_REFRESH,
        description="Small transaction channel reference dimension.",
        source_names=("transactions",),
        required_columns=("trans_type_key",),
        unique_key=("trans_type_key",),
    ),
    "trans_error_type_dimension": GoldDatasetContract(
        name="trans_error_type_dimension",
        schema=TransErrorTypeDimensionSchema,
        staging_path="gold/_staging/trans_error_type_dimension",
        publish_path="gold/trans_error_type_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.FULL_REFRESH,
        description="Small transaction error reference dimension.",
        source_names=("transactions",),
        required_columns=("trans_error_type_key",),
        unique_key=("trans_error_type_key",),
    ),
    "currency_dimension": GoldDatasetContract(
        name="currency_dimension",
        schema=CurrencyDimensionSchema,
        staging_path="gold/_staging/currency_dimension",
        publish_path="gold/currency_dimension",
        load_strategy=GoldLoadStrategy.FULL,
        refresh_cadence=RefreshCadence.ONE_TIME,
        description="Static ISO currency reference snapshot.",
        required_columns=("currency_key",),
        unique_key=("currency_key",),
    ),
    "account_transaction_fact": GoldDatasetContract(
        name="account_transaction_fact",
        schema=AccountTransactionFactSchema,
        staging_path="gold/_staging/account_transaction_fact",
        publish_path="gold/account_transaction_fact",
        load_strategy=GoldLoadStrategy.PARTITION_OVERWRITE,
        refresh_cadence=RefreshCadence.FIVE_MINUTES,
        description="Dashboard-facing transaction fact refreshed by bounded windows.",
        source_names=("transactions",),
        dependency_names=(
            "customer_dimension",
            "account_dimension",
            "transaction_type_dimension",
            "merchant_dimension",
            "location_dimension",
            "trans_error_type_dimension",
            "currency_dimension",
        ),
        required_columns=(
            "transaction_id",
            "date_key",
            "time_key",
            "customer_key",
            "account_key",
            "transaction_type_key",
            "merchant_key",
            "merchant_location_key",
            "trans_error_type_key",
            "currency_key",
            "transaction_amount",
        ),
        unique_key=("transaction_id",),
        partition_columns=("date_key",),
        row_count_source="transactions",
        reconciliation_rules=(
            ReconciliationRule(
                name="amount_reconciliation",
                source_name="transactions",
                source_column="amount",
                target_column="transaction_amount",
            ),
        ),
    ),
    "account_monthly_snapshot_fact": GoldDatasetContract(
        name="account_monthly_snapshot_fact",
        schema=AccountMonthlySnapshotFactSchema,
        staging_path="gold/_staging/account_monthly_snapshot_fact",
        publish_path="gold/account_monthly_snapshot_fact",
        load_strategy=GoldLoadStrategy.PARTITION_OVERWRITE,
        refresh_cadence=RefreshCadence.PERIODIC,
        description="Periodic monthly account aggregate, not a 5-minute dashboard table.",
        dependency_names=("account_transaction_fact",),
        required_columns=(
            "month_end_date_key",
            "account_key",
            "customer_key",
            "currency_key",
            "transaction_count",
        ),
        unique_key=("month_end_date_key", "account_key", "currency_key"),
        partition_columns=("month_end_date_key",),
    ),
    "temporal_trend_fact": GoldDatasetContract(
        name="temporal_trend_fact",
        schema=TemporalTrendFactSchema,
        staging_path="gold/_staging/temporal_trend_fact",
        publish_path="gold/temporal_trend_fact",
        load_strategy=GoldLoadStrategy.PARTITION_OVERWRITE,
        refresh_cadence=RefreshCadence.FIVE_MINUTES,
        description="Dashboard-facing trend aggregate refreshed from transaction windows.",
        dependency_names=("account_transaction_fact",),
        required_columns=("date_key", "time_key", "merchant_key", "number_transaction"),
        unique_key=("date_key", "time_key", "merchant_key"),
        partition_columns=("date_key",),
    ),
    "account_owner_factless": GoldDatasetContract(
        name="account_owner_factless",
        schema=AccountOwnerFactlessSchema,
        staging_path="gold/_staging/account_owner_factless",
        publish_path="gold/account_owner_factless",
        load_strategy=GoldLoadStrategy.CDC_UPSERT,
        refresh_cadence=RefreshCadence.CDC,
        description="Mutable account-customer relationship table.",
        source_names=("cards",),
        dependency_names=("customer_dimension", "account_dimension"),
        required_columns=(
            "customer_key",
            "account_key",
            "valid_from_date",
            "valid_to_date",
            "is_active",
        ),
        unique_key=("customer_key", "account_key", "valid_from_date"),
        cdc_key=("customer_key", "account_key", "valid_from_date"),
    ),
}
