#!/bin/bash
set -euo pipefail

# ===========================================
# Refreshes scripts/.env.runtime from Terraform outputs for the dev
# environment. Use this after _dev_setup.sh, or whenever the runtime env file
# is missing/stale but the dev infrastructure already exists.
# ===========================================

ROOT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TR_PLATFORM_DIR="$ROOT_PATH/terraform/environments/dev/platform"
TR_COMPUTE_DIR="$ROOT_PATH/terraform/environments/dev/compute"
RUNTIME_ENV="$ROOT_PATH/scripts/.env.runtime"

cd "$ROOT_PATH"
if [ -f scripts/.env ]; then
  source scripts/.env
fi

ECR_IMAGE_URI="${ECR_IMAGE_URI:-emr712-spark356-python312:latest}"
TF_BACKEND_BUCKET="${TF_BACKEND_BUCKET:-finance-transaction-tf-state-dev-0306}"
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
TF_BACKEND_REGION="${TF_BACKEND_REGION:-$AWS_REGION}"
py_package="${py_package:-aws_pipeline-0.0.1-py3-none-any.whl}"

require_remote_backend_config() {
  if [ -z "${TF_BACKEND_BUCKET:-}" ]; then
    echo "Missing TF_BACKEND_BUCKET. Run terraform/bootstrap first, then export the state bucket name."
    exit 1
  fi
}

terraform_init_remote_backend() {
  local stack_key="$1"

  require_remote_backend_config
  terraform init \
    -input=false \
    -reconfigure \
    -backend-config="bucket=$TF_BACKEND_BUCKET" \
    -backend-config="key=$stack_key" \
    -backend-config="region=$TF_BACKEND_REGION" \
    -backend-config="use_lockfile=true" \
    -backend-config="encrypt=true"
}

echo "Reading platform outputs..."
cd "$TR_PLATFORM_DIR"
terraform_init_remote_backend "dev/platform/terraform.tfstate"
datalake_bucket_name=$(terraform output -raw data_lake_bucket_name)
datalake_bucket_uri=$(terraform output -raw data_lake_bucket_uri)
codebase_bucket_name=$(terraform output -raw code_bucket_name)
ecr_repository_url=$(terraform output -raw ecr_repository_url)

echo "Reading compute outputs..."
cd "$TR_COMPUTE_DIR"
terraform_init_remote_backend "dev/compute/terraform.tfstate"
execution_role_arn=$(terraform output -raw emr_execution_role_arn)
application_id=$(terraform output -raw emr_application_id)

full_ecr_image_uri="${ecr_repository_url%/}:${ECR_IMAGE_URI##*:}"
s3_py_package="s3://$codebase_bucket_name/packages/$py_package"

cat > "$RUNTIME_ENV" <<EOF
# Generated by scripts/refresh_runtime_env_dev.sh from Terraform outputs.
# Do not edit by hand unless you intentionally want to override dev runtime values.
DATALAKE_BUCKET_NAME=$datalake_bucket_name
CODEBASE_BUCKET_NAME=$codebase_bucket_name
FULL_ECR_IMAGE_URI=$full_ecr_image_uri
EXECUTION_ROLE_ARN=$execution_role_arn
APPLICATION_ID=$application_id
DATALAKE_BUCKET_URI=$datalake_bucket_uri
S3_PY_PACKAGE=$s3_py_package
EOF

echo "Runtime variables written to: $RUNTIME_ENV"
